interface ResponsiveImageProps {
  /** Base name of the derivative set, e.g. "children" for /img/children-720.avif. */
  name: string;
  /** Widths generated by scripts/optimize-images.mjs for this image. */
  widths: readonly number[];
  /** Width used when the layout is at its largest — also the fallback `src`. */
  fallbackWidth: number;
  alt: string;
  /** Intrinsic dimensions of the fallback, to reserve space and keep CLS at zero. */
  width: number;
  height: number;
  sizes: string;
  /** True for the LCP element. Preloads instead of lazy-loading. */
  priority?: boolean;
  className?: string;
}

/**
 * A responsive picture built from pre-generated AVIF/WebP derivatives.
 *
 * Deliberately NOT next/image.
 *
 * next/image resizes on demand through a runtime image optimizer. That is the wrong shape
 * here for two reasons: the containers scale to zero, so the first request would pay a
 * cold start AND an image transform; and the public pages are destined for a CDN edge
 * cache (DECISIONS.md D038), which works best when every asset is a static file with a
 * stable URL.
 *
 * The build-time script produces the derivatives; this component just points at them.
 *
 * WHY IT EXISTS AT ALL: the first version hardcoded a single 1080w source. Lighthouse
 * mobile measured LCP at 2.9 s against a 2.5 s budget, because a 390px phone was
 * downloading the 1080px file. Pre-optimising the images silently discarded the responsive
 * behaviour next/image would have given for free.
 */
export function ResponsiveImage({
  name,
  widths,
  fallbackWidth,
  alt,
  width,
  height,
  sizes,
  priority = false,
  className,
}: ResponsiveImageProps) {
  const srcSet = (format: "avif" | "webp") =>
    widths.map((w) => `/img/${name}-${w}.${format} ${w}w`).join(", ");

  return (
    <picture>
      {/* AVIF first: roughly half the bytes of equivalent WebP at the same quality. */}
      <source type="image/avif" srcSet={srcSet("avif")} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet("webp")} sizes={sizes} />
      <img
        src={`/img/${name}-${fallbackWidth}.webp`}
        alt={alt}
        width={width}
        height={height}
        sizes={sizes}
        loading={priority ? "eager" : "lazy"}
        // fetchPriority high on the LCP element tells the browser to request it before
        // other subresources rather than in document order.
        fetchPriority={priority ? "high" : "auto"}
        // Always async, including for the LCP element.
        //
        // `decoding="sync"` looks like the right call for an image you want painted
        // first, and it is not: it blocks presentation until the full decode completes.
        // AVIF is CPU-heavy, and on a throttled mobile profile that measured as 2446 ms
        // of LCP "render delay" with 0 ms of load time — the bytes had already arrived
        // and the browser was simply waiting to finish decoding them.
        decoding="async"
        className={className}
      />
    </picture>
  );
}

/** Widths produced by scripts/optimize-images.mjs. Keep in step with that script. */
export const IMAGE_WIDTHS = {
  children: [360, 540, 720, 1080, 1440],
  headshot: [240, 320, 480, 640, 960],
} as const;
